App\Packages\Greetings\Domain\Greeting:
  collectionOperations:
      post:
          method: 'POST'
          path: '/greetings.{_format}'
          read: false
          deserialize: false
          controller: App\Controller\Greetings\CreateGreetingController
          output: App\Packages\Greetings\Application\DTO\GreetingDTO
          openapi_context:
              requestBody:
                  content:
                      application/json:
                          schema:
                              type: 'object'
                              properties:
                                  name:
                                      type: 'string'
          normalization_context:
              groups: [ 'greeting:readItem' ]
              
  itemOperations:
      get:
          method: 'GET'
          path: '/greetings/{id}.{_format}'
          read: false
          controller: App\Controller\Greetings\GetGreetingByIdController
          output: App\Packages\Greetings\Application\DTO\GreetingDTO
          normalization_context:
              groups: [ 'greeting:readItem' ]

  attributes:
    pagination_client_items_per_page: true
    pagination_items_per_page: 1000
    pagination_maximum_items_per_page: 1000
